version: '3.1'

services:
        db:
                image: postgres:latest
                environment:
                        POSTGRES_PASSWORD: foo

        foo:
                build:
                        context: .
                        dockerfile: docker/restful/Dockerfile
                image: restful
                environment:
                        DATABASE_URL: "host=db user=postgres password=foo sslmode=disable"
                ports:
                        - 8080:8080
                depends_on:
                        - db
